### ISSUE TITLE
unit test error on s390x arch

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#166]
Hell Jerome, I am preparing an upload to debian of the 0.10.2 version with the test activated.

Here a problem observed on the s390x architectures.
I will try to do a source upload and see the resulton the buildd.

Cheers

Fred

======================================================================
ERROR: test_writer (test_io.testHDF5Writer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/picca/pyfai.git/test/test_io.py", line 101, in test_writer
    writer.write(data[i % m], i)
  File "/home/picca/pyfai.git/build/lib.linux-s390x-2.7/pyFAI/io.py", line 391, in write
    self.dataset[index] = I
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 551, in __setitem__
    self.id.write(mspace, fspace, val, mtype)
  File "h5d.pyx", line 217, in h5py.h5d.DatasetID.write (h5py/h5d.c:3065)
  File "_proxy.pyx", line 132, in h5py._proxy.dset_rw (h5py/_proxy.c:1736)
  File "_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite (h5py/_proxy.c:1471)
IOError: can't prepare for writing data (Dataset: Write failed)

======================================================================
FAIL: test_numpy_vs_cython_vs_csr_1d (test_histogram.TestHistogram1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/picca/pyfai.git/test/test_histogram.py", line 179, in test_numpy_vs_cython_vs_csr_1d
    self.assert_(delta_max < 0.55, "Intensity count difference numpy/csr : max delta=%s" % delta_max)
AssertionError: Intensity count difference numpy/csr : max delta=0.553961600966

======================================================================
FAIL: test_separate (test_azimuthal_integrator.TestAzimPilatus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/picca/pyfai.git/test/test_azimuthal_integrator.py", line 60, in test_separate
    self.assert_(amorphous.max()<bragg.max(), "bragg is more intense than amorphous")
AssertionError: bragg is more intense than amorphous

======================================================================
FAIL: testSolidAngle (test_geometry.TestSolidAngle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/picca/pyfai.git/test/test_geometry.py", line 90, in testSolidAngle
    self.assert_(delta_I < 5, 'Error on (good) I are small: %s <5' % delta_I)
AssertionError: Error on (good) I are small: 2142457836.61 <5

----------------------------------------------------------------------

**Comment by picca** [comment]
Here all the build log

https://buildd.debian.org/status/package.php?p=pyfai&suite=experimental

**Comment by kif** [comment]
Hi Fred,

Best wishes and happy new year !

Two weeks away from pyFAI ... sorry for that :-)

I will comment on them ...

> Traceback (most recent call last):
>   File "/home/picca/pyfai.git/test/test_io.py", line 101, in test_writer
>     writer.write(data[i % m], i)
>   File "/home/picca/pyfai.git/build/lib.linux-s390x-2.7/pyFAI/io.py", line 391, in write
>     self.dataset[index] = I
>   File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 551, in __setitem__
>     self.id.write(mspace, fspace, val, mtype)
>   File "h5d.pyx", line 217, in h5py.h5d.DatasetID.write (h5py/h5d.c:3065)
>   File "_proxy.pyx", line 132, in h5py._proxy.dset_rw (h5py/_proxy.c:1736)
>   File "_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite (h5py/_proxy.c:1471)
> IOError: can't prepare for writing data (Dataset: Write failed)

this is probably a h5py bug ...

> ======================================================================
> FAIL: test_numpy_vs_cython_vs_csr_1d (test_histogram.TestHistogram1d)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/picca/pyfai.git/test/test_histogram.py", line 179, in test_numpy_vs_cython_vs_csr_1d
>     self.assert_(delta_max < 0.55, "Intensity count difference numpy/csr : max delta=%s" % delta_max)
> AssertionError: Intensity count difference numpy/csr : max delta=0.553961600966

This is a well known bug. It is related to the bin boundary calculation when performed in float or double.
For now I relaxed the constrains of the test to   0.569 a month ago:
2fd44bcd test/test_histogram.py (Jerome Kieffer 2014-12-04 18:31:29 +0100 182)         self.assert_(delta_max < 0.569, "Intensity count difference numpy/csr : max delta=%s" % delta_max)

> ======================================================================
> FAIL: test_separate (test_azimuthal_integrator.TestAzimPilatus)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/picca/pyfai.git/test/test_azimuthal_integrator.py", line 60, in test_separate
>     self.assert_(amorphous.max()<bragg.max(), "bragg is more intense than amorphous")
> AssertionError: bragg is more intense than amorphous

needs investigation
> 
> ======================================================================
> FAIL: testSolidAngle (test_geometry.TestSolidAngle)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/picca/pyfai.git/test/test_geometry.py", line 90, in testSolidAngle
>     self.assert_(delta_I < 5, 'Error on (good) I are small: %s <5' % delta_I)
> AssertionError: Error on (good) I are small: 2142457836.61 <5

also, another bug which needs investigation.

Cheers,

-- 
Jerome Kieffer <Jerome.Kieffer@terre-adelie.org>

**Comment by picca** [comment]
Hello Jerome,

> Best wishes and happy new year !

thanks and happy news year :)

> Two weeks away from pyFAI ... sorry for that :-)

enjoy your holydais :)


You should have a look all the build log :).
There is not that much problem even if for now only the amg64 architectures are working.
It seems to me thaht the hMemorry Error is an transitory error due to the amount of memory available during the build process.

Nevertheless it would be nice to run the test in verbose mode by default.
Is it possible to activate the versobse by default ?

there is some segfault which could be easier to track with the verbose mode activated.

> Traceback (most recent call last):
> File "/home/picca/pyfai.git/test/test_io.py", line 101, in test_writer
> writer.write(data[i % m], i)
> File "/home/picca/pyfai.git/build/lib.linux-s390x-2.7/pyFAI/io.py", line 391, in write
> self.dataset[index] = I
> File "/usr/lib/python2.7/dist-packages/h5py/_hl/dataset.py", line 551, in __setitem__
> self.id.write(mspace, fspace, val, mtype)
> File "h5d.pyx", line 217, in h5py.h5d.DatasetID.write (h5py/h5d.c:3065)
> File "_proxy.pyx", line 132, in h5py._proxy.dset_rw (h5py/_proxy.c:1736)
> File "_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite (h5py/_proxy.c:1471)
> IOError: can't prepare for writing data (Dataset: Write failed)

this is probably a h5py bug ...

or the requested file try to write somwhere not allow on the build system.

Is it possible to log the patch of the output file where the write happend ?

> This is a well known bug. It is related to the bin boundary calculation when performed in float or double.
> For now I relaxed the constrains of the test to 0.569 a month ago:
> 2fd44bcd test/test_histogram.py (Jerome Kieffer 2014-12-04 18:31:29 +0100 182) self.assert_(delta_max < 0.569, "Intensity count difference numpy/csr : max delta=%s" % delta_max)

When you think that you have something not release but testable we can upload a pyfai 0.10.2+git201501xx just to run all tests on all architectures.

> ======================================================================
> FAIL: test_separate (test_azimuthal_integrator.TestAzimPilatus)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "/home/picca/pyfai.git/test/test_azimuthal_integrator.py", line 60, in test_separate
> self.assert_(amorphous.max()<bragg.max(), "bragg is more intense than amorphous")
> AssertionError: bragg is more intense than amorphous

> needs investigation

This is indeed strange and can be reproduce on multiple architectures.

> > ======================================================================
>> FAIL: testSolidAngle (test_geometry.TestSolidAngle)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "/home/picca/pyfai.git/test/test_geometry.py", line 90, in testSolidAngle
> self.assert_(delta_I < 5, 'Error on (good) I are small: %s <5' % delta_I)
> AssertionError: Error on (good) I are small: 2142457836.61 <5

> also, another bug which needs investigation.


I am wondering if this is not a problem of big/little endian.

Cheers

Fred

**Comment by kif** [comment]
tested on PPC64. test passes (once fabio is updated)
