### ISSUE TITLE
mar345 problem of mask

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#170]
when playing with the mar 345, I got this error

Traceback (most recent call last):
  File "C:\Python27\Scripts\pyFAI-calib.py", line 58, in <module>
    c.preprocess()
  File "C:\Python27\lib\site-packages\pyFAI\calibration.py", line 1123, in preprocess
    AbstractCalibration.preprocess(self)
  File "C:\Python27\lib\site-packages\pyFAI\calibration.py", line 550, in preprocess
    wavelength=self.ai.wavelength)
  File "C:\Python27\lib\site-packages\pyFAI\peak_picker.py", line 89, in __init__
    min_valid = view[numpy.where(flat_mask == False)].min()
IndexError: index 5290000 is out of bounds for size 5290000

**Comment by kif** [comment]
On Thu, 05 Feb 2015 03:42:40 -0800
picca <notifications@github.com> wrote:

> when playing with the mar 345, I got this error
[...]
> IndexError: index 5290000 is out of bounds for size 5290000

I tested with the image from the benchmark which is a 3450x3450.
it was running OK.

I guess your image has been taken with the 2300x2300 mode ?
can you confirm ?

-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>

**Comment by kif** [comment]
Even with an image 2300x2300 (the one in the test set from FabIO),
I did not manage to reporduce the bug.
Can you send me the image + command line used ?

Thanks.

-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>

**Comment by picca** [comment]
Ok, I sent you the image.
now  after conversion with fabio into edf I could calibrate the image. here the poni

# Nota: C-Order, 1 refers to the Y axis, 2 to the X axis 
# Calibration done at Thu Feb 12 14:46:09 2015
Detector: Mar345
PixelSize1: 0.00015
PixelSize2: 0.00015
Distance: 0.446642915189
Poni1: 0.228413453499
Poni2: 0.272291324302
Rot1: 0.0233130647508
Rot2: 0.0011735285628
Rot3: -7.22446379865e-08
SplineFile: None
Wavelength: 7e-11


now when I try to integrate with this code

ai = pyFAI.load(PONI)
ai.integrate1d(image, 2000)



  File "C:/Users/reguer/.nexpy/plugins/carto/treatment.py", line 40, in <module>
    traitement(PONI, FILES)

  File "C:/Users/reguer/.nexpy/plugins/carto/treatment.py", line 38, in traitement
    print ai.integrate1d(dataframe.image, 2000)

  File "C:\Python27\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 2264, in integrate1d
    mask_checksum=mask_crc, unit=unit)

  File "C:\Python27\lib\site-packages\pyFAI\azimuthalIntegrator.py", line 1041, in setup_LUT
    assert mask.shape == shape

AssertionError

**Comment by picca** [comment]
If I force the mask with the right size 2300, 2300 with

ai.integrate1d(dataframe.image, 2000, mask=mask)

it works

**Comment by kif** [comment]
Hi Fred,

Sorry, I have been on holiday for a week...
The problem with mar345 is that even with a pixel size of 150µm, the image could be of:
of size: 2300, 2000, 1600, 1200 which is not easily solvable ...

**Comment by picca** [comment]
holydays should be forbiden ;)
