### ISSUE TITLE
wavelength not taken into account

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#174]
When I load a calibration file like

ai = pyFAI.loaf('toto.poni")

and do the integration with
x, y = ai.integrate(images, N)
the wavelength is not taken into account

I need to write

ai.wavelength = wavelength before doing the integration.

I think that this is a bug and that the wavelength should be taken from the poni file

**Comment by kif** [comment]
On Fri, 13 Feb 2015 03:04:41 -0800
picca <notifications@github.com> wrote:


> I think that this is a bug and that the wavelength should be taken from the poni file

Are you sure ? It should work.

Just print the AzimuthalIntegrator object to check if the wavelength is present
-- 
J�r�me Kieffer <jerome.kieffer@terre-adelie.org>

**Comment by carichte** [comment]
I have a similar issue:

I have many powder diffraction images for different wavelentghs. 
If I want to do integration in q-space in a loop:

`
for im in images:
    energy = ...smth..
    Ai.set_wavelength(hc/energy)
    tth, I = Ai.integrate1d(im.data, 1000, unit="q_nm^-1", radial_range=(7.5,37.5))
`

it only seems to update the wavelength for the first iteration. After that, the actual value of energy doesn't seem to have an influence. I'm using version 0.11 though. Might be fixed already?

**Comment by kif** [comment]
On Tue, 15 Mar 2016 09:07:20 -0700
Carsten Richter <notifications@github.com> wrote:

> I have a similar issue:
> 
> I have many powder diffraction images for different wavelentghs. 
> If I want to do integration in q-space in a loop:
> 
> `
> for im in images:
>     energy = ...smth..
>     Ai.set_wavelength(hc/energy)
>     tth, I = Ai.integrate1d(im.data, 1000, unit="q_nm^-1",
> radial_range=(7.5,37.5)) `
> 
> it only seems to update the wavelength for the first iteration. After
> that, the actual value of energy doesn't seem to have an influence.
> I'm using version 0.11 though. Might be fixed already?

Hi Carsten,

This is typically related to the reset of the geometry arrays when changing the wavelength.
You can manually reset all arrays by calling: 
  Ai.reset()

For a wavelength change only the q-arrays has to be resetted (2th, r, ... don't need a reset)
and this has last been changed on: 2012-06-07.

I will further test today as it is directly related to #265.

Cheers,

Jerome

**Comment by carichte** [comment]
Hi Jerome,

thanks. .reset() helped. The runtime was significantly increased, but in this case it was not a problem for me.
Intuitively, I didn't expect anything should change on the azimuthal integrator on wavelength change, since I saw it as a representation of geometry. I rather assumed it will only take the wavelength into account when performing the conversion from tth to q.

Cheers,
Carsten

**Comment by kif** [comment]
On Thu, 17 Mar 2016 16:15:32 -0700
Carsten Richter <notifications@github.com> wrote:

> Hi Jerome,
> 
> thanks. .reset() helped. The runtime was significantly increased, but in this case it was not a problem for me.
> Intuitively, I didn't expect anything should change on the azimuthal integrator on wavelength change, since I saw it as a representation of geometry. I rather assumed it will only take the wavelength into account when performing the conversion from tth to q.

Hi Carsten,

Your analysis is correct: any change in the parameter set (dist, poni1, poni2, rot1, rot2 rot3) triggers the full reset of all cached arrays.
A change of wavelength resets q-arrays (but not r ot 2theta) and q-values are directly calculated from parameters (and not from 2theta), but sine is not a linear function.

Your suggestion is feasible for q but not other derived arrays (delta-q, ...) this may help a bit.

Cheers,

Jerome
