### ISSUE TITLE
add a way to start the calibration process from a numpy array

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#182]
it would be nice to have:

poni = pyFAI.calibrate(img, ...)

this would start the calibration process from the command line.
a nice feature would be also to return an objet which represent a poni structure

this poni object could be used later to initialize an integrator

ai = pyFAI.load(poni(object))

this way it would be possible to create a collection of poni object which can be used to do the integration for different angles.

[poni1, poni2, poni3, ...] -> [ai1, ai2, a3, ...]

**Comment by kif** [comment]
I started with smth like this. It would be more sensible to return the AI directly.
import pyFAI
import pyFAI.calibration
import fabio
img=fabio.open("test/testimages/Pilatus1M.edf").data
det=pyFAI.detectors.Pilatus1M()
cal=pyFAI.calibrant.ALL_CALIBRANTS("AgBh")
cal.wavelength=1e-10
print(cal.get_2th())
pyFAI.calibration.calib(img, cal, det, reconstruct=True)
