### ISSUE TITLE
issue with Python3.4

### ISSUE THREAD

**Issue by kif** [kif/pyFAI#206]
this is about relative imports. one may rethink how tests are launched.

**Comment by kif** [comment]
python3.3 could be affected

**Comment by kif** [comment]
Mind to run cython3 on all pyx files of the src directory:
* cython3 src/*.pyx
* ./update_openmp.sh 3

**Comment by picca** [comment]
Here something found during the debian pacakging

Removing /«BUILDDIR»/pyfai-0.11.0+dfsg/debian/tmp/usr/lib/python3.4/dist-packages/pyFAI-0.11.0.egg-info
Writing /«BUILDDIR»/pyfai-0.11.0+dfsg/debian/tmp/usr/lib/python3.4/dist-packages/pyFAI-0.11.0.egg-info
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
  File "/usr/lib/python3.4/dist-packages/pyFAI/test/debug_ocl_sort.py", line 24
    print time_sort
                  ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by picca** [comment]
list of missing print in the test directory

only one real in debug_ocl_sort.
the rest are commented code

should we remove or fix also the commented parts ?

debug_ocl_sort.py:print time_sort
profile_lut_pixelsplitFull.py:            #print data_1[j],data_2[j],numpy.allclose(data_1[j],data_2[j]), idx_ptr[i]+j
profile_lut_pixelsplitFull.py:#print aaa,bbb
profile_ocl_lut_pixelsplit2.py:#print lutsize
profile_ocl_lut_pixelsplit.py:            # print data_1[j],data_2[j],numpy.allclose(data_1[j],data_2[j]), idx_ptr[i]+j
profile_ocl_lut_pixelsplit.py:# print aaa,bbb
profile_ocl_lut.py:#print "nodummy/Dummy", utilstest.Rwp((out_cyt[0], out_cyt[1]), (out_cyt[0], nodummy), "nodummy/Dummy")
profile_ocl_lut.py:#print "SolidAngle", solidAngle
profile_ocl_lut.py:#print img
profile_ocl_lut.py:#print "Pol: lut/refR=", utilstest.Rwp((out_cyt[0], xx), out_cyt[:2], "Polarization")
profile_ocl_lut.py:#print "Pol: ocl/refR=", utilstest.Rwp((out_cyt[0], out_ocl), (out_cyt[0], xx), "Polarization")
profile_ocl_lut.py:#print "Pol: noc/refR=", utilstest.Rwp((out_cyt[0], nodummy), (out_cyt[0], xx), "Polarization")
profile_ocl_lut.py:#print out_ocl
profile_pixelsplitFullLUT2.py:            #print data_1[j],data_2[j],numpy.allclose(data_1[j],data_2[j]), idx_ptr[i]+j
profile_pixelsplitFullLUT2.py:#print aaa,bbb
profile_pixelsplitFullLUT.py:            #print data_1[j],data_2[j],numpy.allclose(data_1[j],data_2[j]), idx_ptr[i]+j
profile_pixelsplitFullLUT.py:#print aaa,bbb
profile_pixelsplitFull.py:            #print data_1[j],data_2[j],numpy.allclose(data_1[j],data_2[j]), idx_ptr[i]+j
profile_pixelsplitFull.py:#print aaa,bbb
test_export.py:#    print a1
test_export.py:#        print ref.getFit2D()
test_export.py:#        print ref.getSPD()
test_export.py:#        print obt.getSPD()
test_geometry_refinement.py:#        print tth, wl, ds, 2 * ds[0] * numpy.sin(tth / 2)
test_geometry_refinement.py:#        print "ref", ref2
test_geometry_refinement.py:#        print "obt", r2.param
test_peak_picking.py:#        print self.pp.points
test_peak_picking.py:#        print lstPeak
test_peak_picking.py:#        print self.pp.points
test_polarization.py:#    print numpy.degrees(tth[6])
test_polarization.py:#    print numpy.degrees(chi[6])
test_polarization.py:#    print numpy.degrees(tth[:, 6])
test_polarization.py:#    print numpy.degrees(chi[:, 6])
