### ISSUE TITLE
Please print the rotations angles in degrees

### ISSUE THREAD

**Issue by picca** [kif/pyFAI#215]
Hello Jerome,

I have close to my shoulder mister Elkaim, he would like to see his degree back.
In fact and I agreed with him, when you do a calibration it is better to see rot1, 2, 3 = 7 degree instead of 0.12217294444444445

thanks

**Comment by picca** [comment]
Is it possible to put also this information in the poni file.

**Comment by kif** [comment]
Not the PONI file, definitely not !
For printing on the screen, why not.
