### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by kif** [kif/pyFAI#223]
While set-up under Travis-CI and AppVeyor, it systematically fails...
tesing process got killed due to memory consumption.

**Comment by kif** [comment]
Apparently 3GB of stack memory are needed now to run the tests, which is huge.
find a way to diminish it.

**Comment by Luindil** [comment]
I had the same Problem with Dioptas Travis-CI. What I noticed was, that the memory in each unittest is not properly cleaned when calling the next, even when i specifically instructed python to do so. I ended up with my own unites script, which started a new python instance for each unittest file, and this is working without problems. Before i had the memory consumption stacking up to about 5 GB and now it is only maximum 1.7 for large images.

**Comment by kif** [comment]
On Mon, 31 Aug 2015 23:18:09 -0700
Clemens Prescher <notifications@github.com> wrote:

> I had the same Problem with Dioptas Travis-CI. What I noticed was, that the memory in each unittest is not properly cleaned when calling the next, even when i specifically instructed python to do so. I ended up with my own unites script, which started a new python instance for each unittest file, and this is working without problems. Before i had the memory consumption stacking up to about 5 GB and now it is only maximum 1.7 for large images.

Hi Clemens,

Thanks for the confirmation. 
PyFAI's test crashed (kernel-panic) a production computer last week: there is room for improvement on the test side. 
There were only 2GB memory and no swap (actually the computer is just an enclosure for a network card and a GPU).
I am now playing with valgrind which confirmed a 3GB stack consumption, but little modification already helped a lot.

Cheers,

**Comment by kif** [comment]
Well everything is not yet passing but tests are OK on 2.6 & 2.7. 
Remaining bugs are related to external packages: 
* 3.2 build of numpy&scipy -> rebuild wheels
* 3.3 bug in FabIO fixed upstram -> rebuild wheels
* 3.4 bug in testing infrastructure related to absolute imports which changes in 3.3->3.4
