### ISSUE TITLE
separate on GPU

### ISSUE THREAD

**Issue by kif** [kif/pyFAI#226]
Basically implement the separate (Bragg vs Amorphous) in OpenCL

**Comment by coquellen** [comment]
Super !!!

Merci Jérome,
Vais tester pour NanoPeakCell ;)

Nico.
Jerome Kieffer <notifications@github.com> a écrit :

**Comment by kif** [comment]
On Mon, 21 Sep 2015 13:00:09 -0700
coquellen <notifications@github.com> wrote:

> Super !!!
> 
> Merci Jérome,
> Vais tester pour NanoPeakCell ;)

C'est pas encore pret !

apres separate, tu fais quoi précisement ?

tu compte le nombre de massifs qui sont >theshold ?

A+
-- 
Jérôme Kieffer

**Comment by coquellen** [comment]
Oui, en fait, on détermine la position et l'intensité des pics de  
Bragg (dans une routine différente de separate, et en utilisant un  
bout de code à nous), mais si il y a des outils dans pyFAI, nous  
sommes preneurs ;)

Merci encore,

Nico.
Jerome Kieffer <notifications@github.com> a écrit :

> On Mon, 21 Sep 2015 13:00:09 -0700
