### ISSUE TITLE
log(q) radial units

### ISSUE THREAD

**Issue by kif** [kif/pyFAI#227]
request from id02

**Comment by jonwright** [comment]
Hi Jerome,
I seem to remember 1/d^2 as another recent addition. Maybe people could 
be allowed to supply the function which converts x/y/z detector pixel 
co-ordinates to output unit(s) ?
Cheers
Jon

**Comment by kif** [comment]
Hi Jon,
This sounds like a good idea as we have now available the position in space (in sample/beam referential) the position of any pixel at coordinate i,j.
It is likely the initialization of the radial array will take a lot more time as it has to be numpy code (i.e. not parallel).
