### ISSUE TITLE
xpad_flat

### ISSUE THREAD

**Issue by kif** [kif/pyFAI#235]
the formula for vertical gaps is wrong: there are no "multiple width pixel along the vertical axis:
this is equivalent to subtract 3 pixels vertically per actual gap
@picca

**Comment by picca** [comment]
the s140 should be fixed also, there is no double pixel at the begining and the end of a line.

**Comment by kif** [comment]
I coded a bit in the train ... but the code is not yet pushed.

**Comment by kif** [comment]
closed by 768f82d0
